CREATE TABLE tb_police(
police_id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '报警主键',
user_id BIGINT(20) UNSIGNED NOT NULL COMMENT '报警的用户主键',
opened BIT NOT NULL COMMENT '状态',
police_time TIMESTAMP NOT NULL COMMENT '报警时间',
PRIMARY KEY (police_id)
)ENGINE = InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='报警表';